# Generated by Django 3.2.3 on 2021-05-28 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('feeling', models.CharField(choices=[('joy', '기쁨'), ('angry', '화남'), ('sad', '슬픔'), ('fear', '두려움')], default='joy', max_length=20)),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True, null=True)),
                ('ocr_image', models.ImageField(blank=True, null=True, upload_to='ocr/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
